import type { Metadata } from "next";
import "./globals.css";
import { Nosifer } from "next/font/google";

const newNosifer = Nosifer({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Horror story generator app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${newNosifer.className} antialiased`}>{children}</body>
    </html>
  );
}
